export const ActionTypes = {
    // LOGIN : "LOGIN",
    // LOGOUT:"LOGOUT",
    // GET_USER:"GET_USER",
    // FETCH_USER:"FETCH_USER",
    // UPDATE_USER:"UPDATE_USER",
    FETCH_SHOP:"FETCH_SHOP",
    SET_SLIDERS:"SET_SLIDERS",
    SET_SECTIONS:"SET_SECTION",
    SET_OFFERS:"SET_OFFERS",
    SET_CATEGORY:"SET_CATEGORY",
    // GET_SLIDERS:"GET_SLIDERS",
    // GET_SECTIONS:"GET_SECTION",
    // GET_OFFERS:"GET_OFFERS",
    // GET_CATEGORY:"GET_CATEGORY"
}