export const ActionTypes = {
    //Auth
    SET_AUTH:"SET_AUTH",
    CLEAR_AUTH:"CLEAR_AUTH",
    
    //Alert
    SET_ALERT:"SET_ALERT",
    REMOVE_ALERT:"REMOVE_ALERT",
    
    //Location
    SET_LOCATION:"SET_LOCATION",
    CLEAR_LOCATION:"CLEAR_LOCATION",
    SET_CITY:"SET_CITY",
    
    //User
    GET_USER_DETAILS:"GET_USER_DETAILS",
    
    //Shop
    FETCH_SHOP:"FETCH_SHOP",
    SET_SLIDERS:"SET_SLIDERS",
    SET_SECTIONS:"SET_SECTION",
    SET_OFFERS:"SET_OFFERS",
    SET_BRANDS:"SET_BRANDS",
    
    //Category
    SET_CATEGORY:"SET_CATEGORY",
    SET_CATEGORY_FROM_API:"SET_CATEGORY_FROM_API",


    //Products
    FETCH_PRODUCT_FROM_CATEGORY:"FETCH_PRODUCT_FROM_CATEGORY",
    CLEAR_PRODUCTS:"CLEAR_PRODUCTS",
    ERROR_FETCH_PRODUCTS:"ERROR_FETCH_PRODUCTS",
}