export const ActionTypes = {

    //CSS Mode
    SET_CSSMODE : "SET_CSSMODE",

    //language
    SET_LANGUAGE : "SET_LANGUAGE",
    
    //Sliders
    SET_SLIDERS : "SET_SLIDERS",

    //Location
    SET_CITY:"SET_CITY",

    //Categories
    SET_CATEGORY:"SET_CATEGORY",

    //Authentication
    SET_CURRENT_USER:"SET_CURRENT_USER",
    LOGOUT_AUTH:"LOGOUT_AUTH",

    //product filters
    SET_FILTER_SECTION :"SET_FILTER_SECTION",
    SET_FILTER_BRANDS : "SET_FILTER_BRANDS",
    SET_FILTER_CATEGORY : "SET_FILTER_CATEGORY",
    SET_FILTER_MIN_MAX_PRICE:"SET_FILTER_MIN_MAX_PRICE",
    SET_FILTER_VIEW:"SET_FILTER_VIEW",
    SET_FILTER_SORT:"SET_FILTER_SORT",


}